---
title: "MSE"
author: "Dung Vu Tien Viet"
date: "31 octobre 2018"
output:
  word_document: default
  html_document: default
---

## 1. General formula of MSE

### 1.1. One hospital 

It is characterized by four parameters $(n_c, n_h, p_c, p_h)$ where

* $n_c$ is the number community-acquired infection samples;
* $n_h$ is the number of hospital-acquired infection samples;
* $p_c$ is the prevelance of resistance among community-acquired infections;
* $p_h$ is the prevalence of resistance among hospital-acquired infections.

Our aim is to find the best (in term of MSE) estimator $\hat{p_c}$ of $p_c$.

In absence of information on $n_c$, $n_h$ and $p_h$, the best estimator
of $p_c$ we can get is

$$
\hat{p_c} = \frac{n_c p_c + n_h p_h}{n_c + n_h}
$$
By definition,

$$
\mbox{MSE}\left(\hat{p_c}\right) = \mbox{Var}\left(\hat{p_c}\right) + 
                                   \mbox{Bias}\left(\hat{p_c}\right)^2 =
                 \frac{\hat{p_c} \left(1 - \hat{p_c}\right)} {n_c + n_h} +
                 \left(\hat{p_c} - p_c\right)^2
$$

which gives

$$
\mbox{MSE}\left(\hat{p_c}\right) =
\frac{(n_cp_c+n_hp_h)(n_cq_c+n_hq_h)}{(n_c+n_h)^3} +
\left(\frac{n_hp_h-n_hp_c}{n_c+n_h}\right)^2
$$
with $q_c = 1 - p_c$ and $q_h = 1 - p_h$.


Divise numerator and denominator of variance and bias by $n_h$


$$
variance = \frac{(\frac{n_c}{n_h}p_c+p_h)(\frac{n_c}{n_h}q_c+q_h)}{(n_c+n_h)(\frac{n_c}{n_h}+1)^2}
$$


$$
bias=\left(\frac{p_h-p_c}{\frac{n_c}{n_h}+1}\right)^2
$$


$$
lim_{\frac{n_c}{n_h}\to\infty}(variance)=\frac{p_cp_h}{n_c+n_h}
$$

$$
lim_{\frac{n_c}{n_h}\to 0}(variance)=\frac{q_cq_h}{n_c+n_h}
$$


$$
lim_{\frac{n_c}{n_h}\to\infty}(bias) = 0
$$

$$
lim_{\frac{n_c}{n_h}\to 0}(bias) = (p_h-p_c)^2
$$

$p_h$ and $p_c$ are constant, so

from (4), (6) and (7) we conclude variance depends on ratio $\frac{n_c}{n_h}$ and value of $n_c,\ n_h$

from (5), (8) and (9) we see that bias depends on ratio $\frac{n_c}{n_h}$ and varies in range $[0, (p_h-p_c)^2]$


**Simulation procedure: validation MSE in case of one hospital**

For a fix value of sample size $n_c$ and $n_h$, I will create a figure two compare MSE obtained by formula and by simulation when $p_c$ and $p_h$ vary.

1. Set value for $p_c$, $p_h$, $n_c$ and $n_h$ 

2. calculate $MSE_f$ using (3).

3. For one simulation loop:

    1. generate two random population using $rbinom(n_c,1,p_c)$ and $rbinom(n_h,1,p_h)$ 

		2. Calculate overall resistance proportion $\left(\hat{p_c}\right)$ after merging two populations 
		
		3. Calculate square of difference bewteen overall resistance $\hat{p_c}$ and $p_c$ --> call $MSE_1$
		
		4. Calculate $MSE_2$, ... $MSE_{10000}$
		
		5. Calculate $MSE_{average} = \frac{\sum_{1 \leqslant i  \leqslant 10000}(MSE)}{10000}$ and compare with $MSE obtained by formula$

4. Redo from step 1 to step 3 with other value of $p_c$, $p_h$

5. Make a figure of $p_c$ on x axis, $p_h$ on y axis and two lines of $MSE_{average}$ and $MSE_f$

6. $n_c$ and $n_h$ are still constant. Should we choose only some values: 1000, 2000, 10000?
		
*End of simulation procedure*



### 1.2. In case of $k$ hospitals
Each hospital is characterized by four parameters. 

We suppose the resistance prevalence among CAI ($p_c$) remains constant in all hospitals. 

So the MSE will be represented by a set of parameters $(n_{c1},\dots,n_{ck},n_{h1},\dots,n_{hk},p_c,p_{h1},\dots,p_{hk},)$

$$
\hat{p_c} =\frac{\displaystyle\sum_{1 \leqslant i  \leqslant k}(n_{ci}p_c +n_{hi}p_{hi})}{\displaystyle\sum_{1 \leqslant i  \leqslant k}(n_{ci}+n_{hi})} 
$$

And

$$
\mbox{MSE}\left(\hat{p_c}\right) = \frac{\frac{\sum_{}(n_{ci}p_c +n_{hi}p_{hi})}{\sum_{}(n_{ci}+n_{hi})}\left(1-\frac{\sum_{}(n_{ci}p_c +n_{hi}p_{hi})}{\sum_{}(n_{ci}+n_{hi})}\right)}{\sum_{}(n_{ci}+n_{hi})}+\left(\frac{\sum_{}(n_{ci}p_c +n_{hi}p_{hi})}{\sum_{}(n_{ci}+n_{hi})}-p_c\right)^2
$$


which gives

$$
\mbox{MSE}\left(\hat{p_c}\right) = \frac{\sum_{}(n_{ci}p_c +n_{hi}p_{hi})\sum_{}(n_{ci}q_c +n_{hi}q_{hi})}{(\sum_{}(n_{ci}+n_{hi}))^3} + \left(\frac{\sum_{}n_{hi}(p_{hi}-p_c)}{\sum_{}(n_{ci}+n_{hi})}\right)^2
$$

Assign

Number of resistance patients in hospital i: 
$$
a_i=n_{ci}p_c +n_{hi}p_{hi};
$$
Number of non-resistance patients in hospital i: 
$$
b_i=n_{ci}q_c +n_{hi}q_{hi};
$$
Total patients
$$
a_i+b_i=n_{ci}+n_{hi};
$$
$$
a - n_{hi}(p_{hi}-p_c)=n_{ci}p_c +n_{hi}p_{hi}- n_{hi}(p_{hi}-p_c)=n_{ci}p_c + n_{hi}p_c = (a_i+b_i)p_c
$$
so,
$$
 n_{hi}(p_{hi}-p_c) = a_i-(a_i+b_i)p_c=a_iq_c-b_ip_c
$$

$$
\mbox{MSE}\left(\hat{p_c}\right) = \frac{\sum_{}a_i\sum_{}b_i}{(\sum_{}(a_i+b_i))^3} + \frac{(\sum_{}(a_iq_c-b_ip_c))^2}{(\sum_{}(a_{i}+b_{i}))^2} \ \ \ (1)
$$


## 2. Variation of MSE

We continue to consider following cases:

+ One type of hospital with $t_1$ hospitals

+ Two types of hospital with $t_1$ and $t_2$ hospitals

+ Three types of hospital with $t_1$, $t_2$ and $t_3$ hospitals

Hospitals are considered as same type if they have same parameters.

### 2.1. One type of hospital

Given $t_1$ hospitals having $(n_c,n_h,p_c,p_h),\ q_c=1-p_c,\ q_h=1-p_h$.

using (1), 

$$
MSE=\frac{(t_1a_1)(t_1b_1)}{(t_1(a_1+b_1))^3}+\frac{t_1^2(a_1q_c-b_1p_c)^2}{t_1^2(a_1+b_1)^2}
$$


$$
MSE=\frac{a_1b_1}{t_1(a_1+b_1)^3}+\frac{(a_1q_c-b_1p_c)^2}{(a_1+b_1)^2}
$$


### 2.2. Two types of hospital

Given $t_1$ hospitals having $(n_{c1},n_{h1},p_c,p_{h1}),\ q_c=1-p_c,\ q_{h1}=1-p_{h1}$ and $t_2$ hospitals having $(n_{c2},n_{h2},p_c,p_{h2}),\ q_{h2}=1-p_{h2}$.

$$
MSE=\frac{(t_1a_1+t_2a_2)(t_1b_1+t_2b_2)}
{(t_1(a_1+b_1)+t_2(a_2+b_2))^3} +
\frac{(t_1(a_1q_c-b_1p_c)+t_2(a_2q_c-b_2p_c))^2}
{(t_1(a_1+b_1)+t_2(a_2+b_2))^2}
$$


### 2.3. Three types of hospital

Given $t_1$ hospitals having $(n_{c1},n_{h1},p_c,p_{h1}),\ q_c=1-p_c,\ q_{h1}=1-p_{h1}$, $t_2$ hospitals having $(n_{c2},n_{h2},p_c,p_{h2}),\ q_{h2}=1-p_{h2}$ and  $t_3$ hospitals having $(n_{c3},n_{h3},p_c,p_{h3}),\ q_{h3}=1-p_{h3}$.

$$
MSE=\frac{(t_1a_1+t_2a_2+t_3a_3)(t_1b_1+t_2b_2+t_3b_3)}
{(t_1(a_1+b_1)+t_2(a_2+b_2)+t_3(a_3+b_3))^3} +
\frac{(t_1(a_1q_c-b_1p_c)+t_2(a_2q_c-b_2p_c)+t_3(a_3q_c-b_3p_c))^2}
{(t_1(a_1+b_1)+t_2(a_2+b_2)+t_3(a_3+b_3))^2}
$$

### 2.4. Compare variance, bias and MSE between different models

#### 2.4.1. One type of hospital
We compare first surveillance system ($t_1$ hospitals of type 1) and second system ($t_2$ hospitals of type 1).

$$
\frac{V_2}{V_1}=\frac{\frac{a_1b_1}{t_2(a_1+b_1)^3}}{\frac{a_1b_1}{t_1(a_1+b_1)^3}}=\frac{t_1}{t_2}
$$


$$
B_1=B_2=\frac{(a_1q_c-b_1p_c)^2}{(a_1+b_1)^2}
$$


$$
\frac{MSE_2}{MSE_1} = \frac{V_2+B_2}{V_1+B_1}= \frac{\frac{t_1}{t_2}V_1+B_1}{V_1+B_1}
$$

We note that $MSE_2<MSE_1$ if $t_2>t_1$ and versus.


#### 2.4.2. One type vesus two types of hospital (same number of hospital)

We compare first surveillance system ($t_1+t_2$ hospitals of type 1) and second system ($t_1$ hospitals of type 1 and $t_2$ hospitals of type 2)

$$
\delta_V=\frac{V_2}{V_1}=\frac{\frac{(t_1a_1+t_2a_2)(t_1b_1+t_2b_2)}
{(t_1(a_1+b_1)+t_2(a_2+b_2))^3}}
{\frac{a_1b_1}{(t_1+t_2)(a_1+b_1)^3}}
=
\frac{(t_1a_1+t_2a_2)(t_1b_1+t_2b_2)(t_1+t_2)(a_1+b_1)^3}
{a_1b_1(t_1(a_1+b_1)+t_2(a_2+b_2))^3}
$$
$$
\delta_V=
\frac{(a_1+\frac{t_2}{t_1}a_2)(b_1+\frac{t_2}{t_1}b_2)(1+\frac{t_2}{t_1})(a_1+b_1)^3}
{a_1b_1((a_1+b_1)+\frac{t_2}{t_1}(a_2+b_2))^3}
$$


$$
\delta_B=\frac{B_2}{B_1}=\frac{\frac{(t_1(a_1q_c-b_1p_c)+t_2(a_2q_c-b_2p_c))^2}
{(t_1(a_1+b_1)+t_2(a_2+b_2))^2}}
{\frac{(a_1q_c-b_1p_c)^2}{(a_1+b_1)^2}}
$$

$$
\delta_B=\frac{(t_1(a_1q_c-b_1p_c)+t_2(a_2q_c-b_2p_c))^2(a_1+b_1)^2}
{(t_1(a_1+b_1)+t_2(a_2+b_2))^2(a_1q_c-b_1p_c)^2}
$$
$$
\delta_B=\frac{((a_1q_c-b_1p_c)+\frac{t_2}{t_1}(a_2q_c-b_2p_c))^2(a_1+b_1)^2}
{((a_1+b_1)+\frac{t_2}{t_1}(a_2+b_2))^2(a_1q_c-b_1p_c)^2}
$$

When $\frac{t_2}{t_1} \to 0$

$\delta_V \to 1$ and $\delta_B \to 1$. That means 2 systems are identical

When $\frac{t_2}{t_1} \to \infty$: 
$$
\delta_V \to \frac{a_2b_2(a_1+b_1)^3}{a_1b_1(a_2+b_2)^3}
$$
$$
\delta_B=\frac{(a_2q_c-b_2p_c)^2(a_1+b_1)^2}
{(a_2+b_2)^2(a_1q_c-b_1p_c)^2}
$$

$$
\frac{MSE_2}{MSE_1}=\frac{\delta_VV_2+\delta_BB_2}{V_1+B_1}
$$

#### 2.4.3. Three types of hospital

We compare first surveillance system ($t_1$ hospitals of type 1, $t_2$ hospitals of type 2 and $t_3$ hospitals of type 3) and second surveillance system ($t_4$, $t_5$ and $t_6$ hospitals of type 1, 2 and 3, respectively).

$$
\delta_V=\frac{V_2}{V_1}=\frac{\frac{(t_4a_4+t_5a_5+t_6a_6)(t_4b_4+t_5b_5+t_6b_6)}{(t_4(a_4+b_4)+t_5(a_5+b_5)+t_6(a_6+b_6))^3}}
{\frac{(t_1a_1+t_2a_2+t_3a_3)(t_1b_1+t_2b_2+t_3b_3)}{(t_1(a_1+b_1)+t_2(a_2+b_2)+t_3(a_3+b_3))^3}}
$$
$$
\delta_V=\frac{(t_4a_4+t_5a_5+t_6a_6)(t_4b_4+t_5b_5+t_6b_6)(t_1(a_1+b_1)+t_2(a_2+b_2)+t_3(a_3+b_3))^3}{(t_4(a_4+b_4)+t_5(a_5+b_5)+t_6(a_6+b_6))^3(t_1a_1+t_2a_2+t_3a_3)(t_1b_1+t_2b_2+t_3b_3)}
$$

$$
\delta_B=\frac{B_2}{B_1}=\frac{\frac{(t_4(a_4q_c-b_4p_c)+t_5(a_5q_c-b_5p_c)+t_6(a_6q_c-b_6p_c))^2}
{(t_4(a_4+b_4)+t_5(a_5+b_5)+t_6(a_6+b_6))^2}}
{\frac{(t_1(a_1q_c-b_1p_c)+t_2(a_2q_c-b_2p_c)+t_3(a_3q_c-b_3p_c))^2}
{(t_1(a_1+b_1)+t_2(a_2+b_2)+t_3(a_3+b_3))^2}}
$$
$$
\delta_B=\frac{(t_4(a_4q_c-b_4p_c)+t_5(a_5q_c-b_5p_c)+t_6(a_6q_c-b_6p_c))^2(t_1(a_1+b_1)+t_2(a_2+b_2)+t_3(a_3+b_3))^2}
{(t_4(a_4+b_4)+t_5(a_5+b_5)+t_6(a_6+b_6))^2(t_1(a_1q_c-b_1p_c)+t_2(a_2q_c-b_2p_c)+t_3(a_3q_c-b_3p_c))^2}
$$

> Simulation


2. MSE of 3 hospital types 
We calculate MSE of estimated resistance prevalence of model having three hospital types with $(n_1,n_2,n_3)$ hospitals per type. $n_1:2 \to 3,n_2:0 \to 2,n_3:0\to 1$ hospitals.
We calculate the difference of MSE obtained by two method:
$P_d = \frac{MSE_f-MSE_s}{MSE_s}$

A boxplot will be used to illustrated the variation of this difference. The mean of difference must be equal to 0.


3. Compare two systems

First model has three hospital types with $(n_1, n_2, n_3)$ hospitals per type. $n_1: 2 \to 3, n_2: 0 \to 3, n_3: 0 \to 2$ hospitals.

First model has three hospital types with $(n_4, n_5, n_6)$ hospitals per type. $n_4: 3 \to 4, n_4=5: 0 \to 3, n_6: 0 \to 2$ hospitals.

Resistance prevalence in CAI varies from $0.1 \to 0.3$

Resistance prevalence in HAI of each hospital is randomly chosen from $0.4 \to 0.9$

We compare the $\frac{MSE_2}{MSE_1}$ ratio returned by formula (3) and by simulation.
```{r echo=FALSE}

```


